### ISSUE TITLE
Improving Relationship module

### ISSUE THREAD

**Issue by sio-iago** [sio-iago/project-manager#8]
Points to improve:
+ Match the layout to the updated one (it's bugged now)
+ Improve dashboard to reflect the most recent one

**Comment by rfdeoliveira** [comment]
Hey, @sio-iago !

First of all, I've been playing around with your project since yesterday and I think its a nice and very useful tool, man. Thanks for sharing =)

Also, I've been working on some small changes on this module and I guess I'm going to get them done until tomorrow night. Would you mind if I open a PR?

**Comment by sio-iago** [comment]
Not a problem, feel absolutely free to contribute!

Thank you.

**Comment by rfdeoliveira** [comment]
Nice! Thanks for letting me help ya =)

I only fixed the layout so far. It's more consistent with the main theme of the system, at least o/

Tonight I'm going to work on the data the `Relationship Dashboard` should contain.

**Comment by sio-iago** [comment]
Improvements merged. Closing here..
